### ISSUE TITLE
Questions about MCPQ

### ISSUE THREAD

**Issue by ytyt-lead** [mcpq/mcpq-python#4]
Hi! Thank you very much for this great library. It is very easy to work with and much more functional than MCPI.

I had several questions while using MCPQ. Would you mind answering them?

1. Are there any limitations to using threads to perform parallel operations? For example, if I want to run a certain game mechanic in an infinite loop for each player on the server - does the protocol allow such operations on a large number of players? Hardware limitations are not taken into account, of course :)
2. Is there a way to determine that a left/right click was made on the air, and not on another block? Block_hit events do not occur in this case.
3. Is there a way to change the direction of projectiles (fireball, arrow)? I tried changing different properties like `facing`, `_yaw`, `_pitch` but it didn't work. For example, when I tried to do it like this:
```
fireball = world.spawnEntity('fireball', player.pos)
for _ in range(100):
    fireball.pos = fireball.pos.withX(0).withZ(0)
    print(fireball.pos)
```
Then the projectile position was rewritten, but then under the influence of "external forces" it still changed back:
```
Vec3(x=0, y=102.0, z=0)
Vec3(x=0, y=102.0, z=0)
Vec3(x=0.0, y=102.0, z=1.2384172677993774)
Vec3(x=0, y=102.0, z=0)
Vec3(x=0, y=102.0, z=0)
Vec3(x=0.0, y=102.0, z=1.3880797624588013)
Vec3(x=0, y=102.0, z=0)
Vec3(x=0, y=102.0, z=0)
Vec3(x=0, y=102.0, z=0)
Vec3(x=0, y=102.0, z=0)
Vec3(x=0.0, y=102.0, z=3.2321982383728027)
Vec3(x=0, y=102.0, z=0)
Vec3(x=0.0, y=102.0, z=1.6966577768325806)
```
4. There are a huge number of methods and events in the Bukkit API that are not yet supported in MCPQ. Adding each of them, for example, `CampfireStartEvent` will require you to manually modify the plugin, am I right? So Protobuf in this case is not a silver bullet that allows you to easily create mapping between Python and the Bukkit API? :) So we shouldn't expect full (or almost full) compatibility between MCPQ and Bukkit API?

**Comment by icezyclon** [comment]
> Hi! Thank you very much for this great library. It is very easy to work with and much more functional than MCPI.
> 
> I had several questions while using MCPQ. Would you mind answering them?

Hi, welcome and thank you :smiley: 
Sure, questions are always welcome :wave: 
 
> 1. Are there any limitations to using threads to perform parallel operations? For example, if I want to run a certain game mechanic in an infinite loop for each player on the server - does the protocol allow such operations on a large number of players? Hardware limitations are not taken into account, of course :)

Yes, all multi-threaded operations on the same connection - and multiple connections to the same server - should work out of the box! Protobuf takes care of managing the connection for multiple threads.
I am already using multiple threads as it is, for example, registering an event callback while doing something else in an infinite loop.
So your use case of using one thread per player shouldn't be a problem. If you have a very large amount of players (~16+) then I would recommend to use a worker pool and assign each thread a number of players to work on (e.g., with [pebble](https://pypi.org/project/Pebble/))
Note: Multiple operations on the same player (e.g., reading and modifying their position) will probably still lead to race conditions, but one thread per player seems fine

> 2. Is there a way to determine that a left/right click was made on the air, and not on another block? Block_hit events do not occur in this case.

Not natively at the moment, no.
This would require either native support, i.e., sending a new [event type](https://stackoverflow.com/a/42173231) that triggers on this condition, or by applying your logic with in-game commands whenever a certain item is used (I don't think you can do *any* right or left click via in-game commands)  (e.g. setting up a scoreboard to track carrot_on_a_stick uses, then running `player.runCommand(...)` with a certain condition, but that is probably very ugly and in this case, doesn't even do what you want it to do)

> 3. Is there a way to change the direction of projectiles (fireball, arrow)? I tried changing different properties like `facing`, `_yaw`, `_pitch` but it didn't work. For example, when I tried to do it like this:
> 
> ```
> fireball = world.spawnEntity('fireball', player.pos)
> for _ in range(100):
>     fireball.pos = fireball.pos.withX(0).withZ(0)
>     print(fireball.pos)
> ```
> 
> Then the projectile position was rewritten, but then under the influence of "external forces" it still changed back:

So, it seems that both `pos` and `facing` do work, but then the fireball continues as it has, due to the `Motion` and `power` field in it's nbt data.
Both aren't reset for fireballs just because the fireball got teleported or turned into a different direction.
(Motion is the starting direction in x,y,z values and power is the constant acceleration in the x,y,z direction)
I would recommend something like this for now:
```python
from time import sleep
from mcpq import Minecraft, Vec3
mc = Minecraft()
player = mc.getPlayer()

fireball = player.world.spawnEntity("fireball", player.pos) # spawn fireball
d = Vec3(0, 0, 0)  # stop fireball -> no motion at all
p = Vec3(0, 0, 0) # stop fireball -> no acc
fireball.runCommand(
    f"data merge entity @s {{Motion:[{d.x:f},{d.y:f},{d.z:f}],power:[{p.x:f},{p.y:f},{p.z:f}]}}"
)
sleep(3)
d = player.facing  # after 3 seconds shoot in direction player is currently looking
p = d.norm() * 0.02  # fireball power (constant acceleration) is about 0.02 (higher is faster)
fireball.runCommand(
    f"data merge entity @s {{Motion:[{d.x:f},{d.y:f},{d.z:f}],power:[{p.x:f},{p.y:f},{p.z:f}]}}"
)
```

> 4. There are a huge number of methods and events in the Bukkit API that are not yet supported in MCPQ. Adding each of them, for example, `CampfireStartEvent` will require you to manually modify the plugin, am I right? So Protobuf in this case is not a silver bullet that allows you to easily create mapping between Python and the Bukkit API? :) So we shouldn't expect full (or almost full) compatibility between MCPQ and Bukkit API?

You are right. The plugin has to manually deal with and 'translate' any call from Protobuf logic to Bukkit API calls and back.
I do plan on adding new methods/events eventually but really, the plugin is a curated list of the most useful/accessible features/events.
Adding a lot of stuff always takes some amount of work, for example, documentation and also testing.
For the moment it seems more sensible to add what is the most useful and test it instead of trying to translate the entire Bukkit API. 
(Some stuff isn't event possible with only Bukkit API and would require more dependencies (for example, I really wanted to add a function that would return the output of any command sent similar to what you see in the chat when entering a slash-command, but it's not possible for vanilla in the current setting).)

If there are more requests for a feature I might add it earlier when I have the time, otherwise people are welcome to contribute to the plugin :+1: 

Hope this answers your questions and have fun :grin:

**Comment by ytyt-lead** [comment]
Thank you very much for the answers, they were very helpful!

I am a Python developer (backend), and my knowledge of Kotlin is absolutely zero. Therefore, I am physically unable to help in the development of the plugin :( But I have already recommended your plugin to several interested people, so I hope that at least such help will be useful.
